import type ServerlessConfigurationFunctions from './ServerlessConfigurationFunctions'

type ServerlessConfigurationFunction = ServerlessConfigurationFunctions[string]

export default ServerlessConfigurationFunction
